// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWe1LO_Y510lMEIB9b5r_pJxkATGcSu0s',
    appId: '1:1094871194290:web:02137189f715ea4e8dc7ab',
    messagingSenderId: '1094871194290',
    projectId: 'bowlingfinder',
    authDomain: 'bowlingfinder.firebaseapp.com',
    databaseURL: 'https://bowlingfinder-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bowlingfinder.firebasestorage.app',
    measurementId: 'G-QPC6TGFRDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDoASHa8qD4OuA7vQsKECLk13NGHaDxI',
    appId: '1:1094871194290:android:8b04531482773e7f8dc7ab',
    messagingSenderId: '1094871194290',
    projectId: 'bowlingfinder',
    databaseURL: 'https://bowlingfinder-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bowlingfinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKnYDVp4YWWXbkT1ABp3fsu8aUDMCpIng',
    appId: '1:1094871194290:ios:1adc319f5c39dade8dc7ab',
    messagingSenderId: '1094871194290',
    projectId: 'bowlingfinder',
    databaseURL: 'https://bowlingfinder-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bowlingfinder.firebasestorage.app',
    iosBundleId: 'com.example.bowling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKnYDVp4YWWXbkT1ABp3fsu8aUDMCpIng',
    appId: '1:1094871194290:ios:1adc319f5c39dade8dc7ab',
    messagingSenderId: '1094871194290',
    projectId: 'bowlingfinder',
    databaseURL: 'https://bowlingfinder-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bowlingfinder.firebasestorage.app',
    iosBundleId: 'com.example.bowling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWe1LO_Y510lMEIB9b5r_pJxkATGcSu0s',
    appId: '1:1094871194290:web:9c37102f9568831c8dc7ab',
    messagingSenderId: '1094871194290',
    projectId: 'bowlingfinder',
    authDomain: 'bowlingfinder.firebaseapp.com',
    databaseURL: 'https://bowlingfinder-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bowlingfinder.firebasestorage.app',
    measurementId: 'G-Z7C98J8QT4',
  );
}
