name: bowling
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  firebase_core: ^4.10.0
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  flutter:
    sdk: flutter
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2
  firebase_auth: ^6.5.2
  share_plus: 13.1.0
  image: ^4.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
